name: iChaiwut.me
markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:title
paginate: 7
url: http://ichaiwut.me
imageurl: http://ichaiwut.me/img/
comments: true

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-47772460-1'