# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values: Ukham
      title: Ukham

description: บล็อคเกอร์หัวเกรียนท่านหนึ่ง
author: waizonne@outlook.com
  name: Ukham
  email: waizonne@gmail.com
  github: waizonne
  twitter: waizonne
  pinterest: abhisitu
  linkedin: 
  bio: บล็อคเกอร์หัวเกรียนท่านหนึ่ง
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
